/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagementsystem;

/**
 *
 * @author RG
 */
public class StudentFees extends javax.swing.JFrame {

    /**
     * Creates new form StudentFees
     */
    public StudentFees() {
        initComponents();
        
         setVisible(true);
        setSize(700,500);
        setBounds(450,130, 700,500);
   
       // setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtRoomNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Mobile Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(73, 58, 90, 14);

        jLabel2.setText(" Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(63, 91, 60, 14);

        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(67, 129, 50, 14);

        jLabel4.setText("Room No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(66, 172, 70, 14);

        jLabel5.setText("Month");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 210, 50, 14);

        jLabel6.setText("Amount to be pay");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(66, 250, 110, 14);
        getContentPane().add(txtAmount);
        txtAmount.setBounds(220, 240, 140, 20);
        getContentPane().add(txtMonth);
        txtMonth.setBounds(220, 200, 140, 20);
        getContentPane().add(txtRoomNo);
        txtRoomNo.setBounds(218, 167, 140, 20);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(218, 129, 140, 20);
        getContentPane().add(txtMobile);
        txtMobile.setBounds(218, 55, 140, 20);
        getContentPane().add(txtName);
        txtName.setBounds(218, 91, 140, 20);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        btnSearch.setText("Search");
        getContentPane().add(btnSearch);
        btnSearch.setBounds(376, 51, 110, 29);

        jButton1.setText("Clear");
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 320, 80, 23);

        jButton2.setText("Save");
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 320, 70, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pages background.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-3, 1, 710, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRoomNo;
    // End of variables declaration//GEN-END:variables
}
