/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package facultyinformation;

import bean.FacultyDetailBean;
import db.CommonServices;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Neenadevi
 */
public class FacultyDetail extends javax.swing.JPanel {
    String editSaveFlag;
    ArrayList alstFacuArrayRecords;
    int count=0;
    
    /**
     * Creates new form FacultyDetail
     */
    public FacultyDetail() {
        initComponents();
        
        CommonServices obj=new CommonServices();
        System.out.println("size of arraylist------------"+obj.getAllFacultyRecords().size());
        alstFacuArrayRecords=obj.getAllFacultyRecords();
       if(alstFacuArrayRecords.size()>0)
       {
           FacultyDetailBean obj1=(FacultyDetailBean)alstFacuArrayRecords.get(0);
           showFacultyRecord(obj1);
       }
       //     FacultyDetailBean obj1=(FacultyDetailBean)alstFacuArrayRecords.get(0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtDateofBirth = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtFacultyId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        rbtnMale = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtFacultyName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtSalary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ddlDepartment = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        btnPrevious = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel10.setText("Address");

        jLabel9.setText("Salary");

        jLabel6.setText("Phone No");

        buttonGroup1.add(rbtnMale);
        rbtnMale.setText("Male");

        jLabel4.setText("Date of Birth");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel8.setText("Department");

        jLabel3.setText("Father Name");

        jLabel2.setText("Faculty Name");

        ddlDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Arts", "Bio Science", "Management" }));

        jLabel1.setText("Faculty Id");

        jLabel7.setText("Email Id");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnFemale);
        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender");

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Faculty Information System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnFemale))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDateofBirth, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFatherName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFacultyName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFacultyId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ddlDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmailId, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(31, 31, 31)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFacultyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ddlDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(rbtnMale)
                        .addComponent(jLabel10)
                        .addComponent(rbtnFemale))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnPrevious)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLast))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
       if(count<alstFacuArrayRecords.size()-1)
        {
            count++;
            FacultyDetailBean facbean=(FacultyDetailBean)alstFacuArrayRecords.get(count);
            showFacultyRecord(facbean);
            
        }
    }//GEN-LAST:event_btnNextActionPerformed
     public void showFacultyRecord(FacultyDetailBean obj1)
     {
         System.out.println("id-----"+obj1.getFacultyid());
         System.out.println("name-----"+obj1.getFacultyname());
         System.out.println("father name-----"+obj1.getFathername());
         System.out.println("date of birth-----"+obj1.getDob());
         System.out.println("gender-----"+obj1.getGender());
         System.out.println("phno-----"+obj1.getPhoneno());
         System.out.println("emailid-----"+obj1.getEmailid());
         System.out.println("dept-----"+obj1.getDepartment());
         System.out.println("salary-----"+obj1.getSalary());
         System.out.println("address-----"+obj1.getAddress());
           
                txtFacultyId.setText(String.valueOf(obj1.getFacultyid()));
                txtFacultyName.setText(obj1.getFacultyname());
                txtFatherName.setText(obj1.getFathername());
                txtDateofBirth.setText(obj1.getDob());
                if(obj1.getGender().equals("Male"))
                {
                    rbtnMale.setSelected(true);
                }
                if(obj1.getGender().equals("Female"))
                {
                    rbtnMale.setSelected(false);
                    rbtnFemale.setSelected(true);
                }
                txtPhoneNo.setText(obj1.getPhoneno());
                txtEmailId.setText(obj1.getEmailid());
                ddlDepartment.setSelectedItem(obj1.getDepartment());
                txtSalary.setText(obj1.getSalary());
                txtAddress.setText(obj1.getAddress());
     }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
                CommonServices cs=new  CommonServices();
                int facid=cs.facultyid();
                facid=facid+1;
                System.out.println("facid is ......"+facid);
                
                txtFacultyId.setText(String.valueOf(facid));
                txtFacultyName.setEditable(true);
                txtFatherName.setEditable(true);
                txtDateofBirth.setEditable(true);
                rbtnMale.setEnabled(true);
                rbtnFemale.setEnabled(true);
                txtPhoneNo.setEditable(true);
                txtEmailId.setEditable(true);
                ddlDepartment.setEditable(true);
                txtSalary.setEditable(true);
                txtAddress.setEditable(true);
                clear();
    }//GEN-LAST:event_btnAddActionPerformed
 void clear()
 {
     txtFacultyId.setText("");
        txtFacultyName.setText("");
        txtFatherName.setText("");
        txtDateofBirth.setText("");
        
        rbtnMale.setSelected(false);
        rbtnFemale.setSelected(false);
        
        txtPhoneNo.setText("");
        txtEmailId.setText("");
        ddlDepartment.setSelectedIndex(0);
        txtSalary.setText("");
        txtAddress.setText("");
 }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int facultyid = Integer.parseInt(txtFacultyId.getText());
        String facultyphoneno=txtPhoneNo.getText();
        String  facultysalary=txtSalary.getText();
        String facultyname=txtFacultyName.getText();
        String fathername=txtFatherName.getText();
        String dob=txtDateofBirth.getText();
        String emailid=txtEmailId.getText();
        String address=txtAddress.getText();
        String department=(String)ddlDepartment.getSelectedItem();
        String Gender="";
        if(rbtnFemale.isSelected())
        {
            Gender="Female";
        }
        if(rbtnMale.isSelected())
        {
            Gender="Male";
        
        }
             FacultyDetailBean objBean= new FacultyDetailBean();
             
             objBean.setFacultyid(facultyid);
             objBean.setFacultyname(facultyname);
             objBean.setPhoneno(facultyphoneno);
             objBean.setSalary(facultysalary);
             objBean.setFathername(fathername);
             objBean.setDob(dob);
             objBean.setEmailid(emailid);
             objBean.setAddress(address);
             objBean.setDepartment(department);
             objBean.setGender(Gender);
             CommonServices objdb=new CommonServices();
             System.out.println(" call-------------.");
             String result =objdb.addFacultyRecord(objBean);
             System.out.println("Record---------------"+result);
             if(result.equals("add"))
             {
                 JOptionPane.showMessageDialog(this,"record is inserted");
                 
                txtFacultyId.setEditable(false);
                txtFacultyName.setEditable(false);
                txtFatherName.setEditable(false);
                txtDateofBirth.setEditable(false);
                rbtnMale.setEnabled(false);
                rbtnFemale.setEnabled(false);
                txtPhoneNo.setEditable(false);
                txtEmailId.setEditable(false);
                ddlDepartment.setEditable(false);
                txtSalary.setEditable(false);
                txtAddress.setEditable(false);
             }
             else
             {
                 System.out.println("Record is not inserted");
             }
             
             
             
    }//GEN-LAST:event_btnSaveActionPerformed

//    public void showFacultyRecord(FacultyDetailBean objFaculty)
//    {
//        txtFacultyId.setText(objFaculty.getEmailid());
//        txtFacultyName.setText(objFaculty.getFacultyname());
//        txtFatherName.setText(objFaculty.getFathername());
//        txtDateofBirth.setText(objFaculty.getDob());
//        
//        
//        
//        if(objFaculty.getGender().equals("Male"))
//        {
//            rbtnMale.setSelected(true);
//            
//        }
//        if(objFaculty.getGender().equals("Female"))
//        {
//            rbtnFemale.setSelected(true);
//        }
//        
//        txtPhoneNo.setText(objFaculty.getPhoneno());
//        txtEmailId.setText(objFaculty.getEmailid());
//        ddlDepartment.setName(objFaculty.getDepartment());
//        txtSalary.setText(objFaculty.getSalary());
//        txtAddress.setText(objFaculty.getAddress());
//    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
       
        txtFacultyId.setText("");
        txtFacultyName.setText("");
        txtFatherName.setText("");
        txtDateofBirth.setText("");
        
        rbtnMale.setSelected(false);
        rbtnFemale.setSelected(true);
        
        txtPhoneNo.setText("");
        txtEmailId.setText("");
        ddlDepartment.setSelectedIndex(0);
        txtSalary.setText("");
        txtAddress.setText("");
        
        
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed

       // TODO add your handling code here:
        if(count>0)
        {
            count--;
            FacultyDetailBean facbean=(FacultyDetailBean)alstFacuArrayRecords.get(count);
            showFacultyRecord(facbean);
            
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        count=alstFacuArrayRecords.size()-1;
        FacultyDetailBean facbean=(FacultyDetailBean)alstFacuArrayRecords.get(count);
         showFacultyRecord(facbean);
            
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFacultyId.setEditable(false);
        String facultyid= txtFacultyId.getText();
        String facultyname=txtFacultyName.getText();
        String fathername=txtFatherName.getText();
        String dob=txtDateofBirth.getText();
        String Gender="";
        if(rbtnMale.isSelected())
        {
            Gender="";
           
        }
        if(rbtnFemale.isSelected())
        {
            Gender="";
            
        }
        String phoneno=txtPhoneNo.getText();
        String emailid=txtEmailId.getText();
        String department=(String)ddlDepartment.getSelectedItem();
        String salary=txtSalary.getText();
        String address=txtAddress.getText();
        
             FacultyDetailBean objBean= new FacultyDetailBean();
             
             objBean.setFacultyid(Integer.parseInt(facultyid));
             objBean.setFacultyname(facultyname);
             objBean.setPhoneno(phoneno);
             objBean.setSalary(salary);
             objBean.setFathername(fathername);
             objBean.setDob(dob);
             objBean.setEmailid(emailid);
             objBean.setAddress(address);
             objBean.setDepartment(department);
             objBean.setGender(Gender);
             
             CommonServices cs=new CommonServices();
             String result=cs.updateRecord(objBean,facultyid);
             if(result.equals("update"))
                     {
                         JOptionPane.showMessageDialog(this,"Record is updated");
                         
                     }
             else
             {
                 System.out.println("Record is not updated");
                 
             }
        
        
        
        
        
            
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
     count=0;
        FacultyDetailBean facbean =(FacultyDetailBean)alstFacuArrayRecords.get(count);
               showFacultyRecord(facbean);
              
    }//GEN-LAST:event_btnFirstActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox ddlDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFacultyId;
    private javax.swing.JTextField txtFacultyName;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables

 //   private void addEmployeeRecord(FacultyDetailBean objBean) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
}
