/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package usermaintenance;

import DBOperation.CommonServices;
import bean.UserDetailBean;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jyoti
 */
public class UserDetail extends javax.swing.JPanel {

    /**
     * Creates new form UserDetail
     */
    static int count=0;
     ArrayList alst=null;
    public UserDetail() {
        CommonServices obj = new CommonServices();
        initComponents();
        txtUserID.setEditable(false);
        txtUsername.setEditable(false);
        txtEmailID.setEditable(false);
        txtContact.setEditable(false);
        ddlQuestion.setEditable(true);
        taSecurityAnswer.setEditable(false);
        btnSave.setEnabled(false);
        
        alst =obj.getData();
       
            UserDetailBean bean =(UserDetailBean)alst.get(count);
            display(bean);
        
        
        
    }
    public void display(UserDetailBean bean)
    {
        txtUserID.setText(String.valueOf(bean.getId()));
        txtUsername.setText(bean.getUsername());
        txtEmailID.setText(bean.getEmail());
        txtContact.setText(bean.getContact());
  
        ddlQuestion.setSelectedItem(bean.getSecurity_id());
        taSecurityAnswer.setText(bean.getSecurity_answer());
        String radiobutton = bean.getStatus();
        if(radiobutton.equals("active"))
        {
            rbtnActive.setSelected(true);
        }
        else
        {
            rbtnInActive.setSelected(true);
        }
        dc_D_o_j.setText(bean.getD_o_j());
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        ddlQuestion = new javax.swing.JComboBox();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnInActive = new javax.swing.JRadioButton();
        rbtnActive = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        txtUserID = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSecurityAnswer = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        dc_D_o_j = new datechooser.beans.DateChooserCombo();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder("User Detail"));
        setForeground(new java.awt.Color(0, 204, 255));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        ddlQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is your favorite Color?", "Who is your first Teacher?", "Who is your best friend?" }));

        jLabel6.setText("Security Answer");

        jLabel4.setText("Contact");

        buttonGroup1.add(rbtnInActive);
        rbtnInActive.setText("InActive");

        buttonGroup1.add(rbtnActive);
        rbtnActive.setSelected(true);
        rbtnActive.setText("Active");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel3.setText("Email ID");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setText("User ID");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Normal questions");

        jLabel7.setText("Status");

        jLabel2.setText("Username");

        taSecurityAnswer.setColumns(20);
        taSecurityAnswer.setRows(5);
        jScrollPane1.setViewportView(taSecurityAnswer);

        jLabel8.setText("D.O.J");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddlQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(132, 132, 132)
                                            .addComponent(rbtnActive)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbtnInActive))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dc_D_o_j, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(115, 115, 115)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd)
                                    .addComponent(btnLast))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit)
                                    .addComponent(btnNext))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ddlQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnActive)
                        .addComponent(rbtnInActive))
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dc_D_o_j, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnReset)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnLast)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        clear();
        int id = CommonServices.getMAxRegId()+1;
        txtUserID.setText(""+id);
        txtUserID.setEditable(false);
        txtUsername.setEditable(true);
        txtEmailID.setEditable(true);
        txtContact.setEditable(true);
        ddlQuestion.setEditable(true);
        taSecurityAnswer.setEditable(true);
         btnSave.setEnabled(true);
         
       
 
        btnFirst.setEnabled(false);;
        btnNext.setEnabled(false);
        btnLast.setEnabled(false);
        btnPrevious.setEnabled(false);
        btnReset.setEnabled(false);
         
        
         
         
         
    }//GEN-LAST:event_btnAddActionPerformed

    public UserDetailBean getValues()
    {
         String id= txtUserID.getText();
         String username= txtUsername.getText();
         String email=txtEmailID.getText();
         String contact = txtContact.getText();
         int securityQuestion = ddlQuestion.getSelectedIndex();
         String securityAnswer =taSecurityAnswer.getText();
         String status="";
         if(rbtnActive.isSelected())
         {
             status="active";
         }
         else
         {
             status="inactive";
         }
         String date_of_joining=dc_D_o_j.getText();
         
         UserDetailBean obj = new UserDetailBean();
         obj.setId(Integer.parseInt(id));
         obj.setUsername(username);
         obj.setEmail(email);
         obj.setContact(contact);
         obj.setSecurity_id(securityQuestion);
         obj.setSecurity_answer(securityAnswer);
         obj.setStatus(status);
         return obj;
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
         UserDetailBean obj =getValues();
         CommonServices objCommonServices = new CommonServices();
          String result= objCommonServices.addUserDetail(obj);
         
          if(result.equals("add"))
          {
              JOptionPane.showMessageDialog(this, "Record is inserted");
              txtUserID.setEditable(false);
        txtUsername.setEditable(false);
        txtEmailID.setEditable(false);
        txtContact.setEditable(false);
        ddlQuestion.setEditable(true);
        taSecurityAnswer.setEditable(false);
        btnSave.setEnabled(false);
          }
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        btnAdd.setEnabled(false);
        btnSave.setEnabled(false);
        btnFirst.setEnabled(false);;
        btnNext.setEnabled(false);
        btnLast.setEnabled(false);
        btnPrevious.setEnabled(false);
        btnReset.setEnabled(false);
        txtUserID.setEditable(false);
        txtUsername.setEditable(true);
        txtEmailID.setEditable(true);
        txtContact.setEditable(true);
        ddlQuestion.setEditable(true);
        taSecurityAnswer.setEditable(true);
         btnSave.setEnabled(false);
         
         
         
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        clear();
         
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         UserDetailBean obj =getValues();
        int id = Integer.parseInt(txtUserID.getText());
        String result = CommonServices.updateUserById(obj);
          if(result.equals("valid"))
          {
              JOptionPane.showMessageDialog(this, "Record is updated");
              txtUserID.setEditable(false);
        txtUsername.setEditable(false);
        txtEmailID.setEditable(false);
        txtContact.setEditable(false);
        ddlQuestion.setEditable(true);
        taSecurityAnswer.setEditable(false);
        btnUpdate.setEnabled(false);
        btnAdd.setEnabled(true);
        btnSave.setEnabled(false);
        btnFirst.setEnabled(true);;
        btnNext.setEnabled(true);
        btnLast.setEnabled(true);
        btnPrevious.setEnabled(true);
        btnReset.setEnabled(true);
          }
        
        
        

        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        
        UserDetailBean bean = (UserDetailBean)CommonServices.getFirstRecord();
        
        txtUserID.setText(String.valueOf(bean.getId()));
        txtUsername.setText(bean.getUsername());
        txtEmailID.setText(bean.getEmail());
        txtContact.setText(bean.getContact());
        ddlQuestion.setSelectedIndex(bean.getSecurity_id());
        taSecurityAnswer.setText(bean.getSecurity_answer());
        String status = bean.getStatus();
        if(status.equals("active"))
        {
            rbtnActive.setSelected(true);
        }
        else
        {
            rbtnInActive.setSelected(true);
        }
        dc_D_o_j.setText(bean.getD_o_j());
        
        
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        count++;
         UserDetailBean bean =(UserDetailBean)alst.get(count);
            display(bean);
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
          count--;
         UserDetailBean bean =(UserDetailBean)alst.get(count);
            display(bean);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
          int code= DBOperation.CommonServices.getMAxRegId();
         UserDetailBean bean =(UserDetailBean)alst.get(code);
            display(bean);
    }//GEN-LAST:event_btnLastActionPerformed

    public void clear()
    {
         txtUserID.setText("");
         
        txtUsername.setText("");
        txtEmailID.setText("");
        txtContact.setText("");
        ddlQuestion.setSelectedItem("");
        taSecurityAnswer.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dc_D_o_j;
    private javax.swing.JComboBox ddlQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnActive;
    private javax.swing.JRadioButton rbtnInActive;
    private javax.swing.JTextArea taSecurityAnswer;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
