/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Mainwindow;

import bean.Add_Book_EntryData;
import db.newpackage.DBOperation;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SAGAR
 */
public class Add_Book_Entry extends javax.swing.JPanel {
    

    /**
     * Creates new form Add_Books_Entry
     */
    ArrayList alst = new ArrayList();
    DBOperation objAdd_Book_Entry = new DBOperation();
    int count = 0;
    public Add_Book_Entry() 
    {
        
        initComponents();
        
        alst = objAdd_Book_Entry.getAllDetailList();
        if(alst.size()>0)
        {
            Add_Book_EntryData bean = (Add_Book_EntryData)alst.get(count);
            showRecord(bean);
        }
        
    }
    public void  showRecord(Add_Book_EntryData objBean)
    {
          txtBook_ID.setText(String.valueOf(objBean.getBook_ID()));
          txtBook_Name.setText(objBean.getBook_Name());
          txtBook_Author.setText(objBean.getBook_Author());
          txtBook_Publication.setText(objBean.getBook_Publication());
          txtBook_Supplier.setText(objBean.getBook_Supplier());
          txtBook_Cost.setText(String.valueOf(objBean.getBook_Cost()));
          txtDepartment_Name.setText(objBean.getDepartment_Name());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBook_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBook_Name = new javax.swing.JTextField();
        txtBook_Author = new javax.swing.JTextField();
        txtBook_Publication = new javax.swing.JTextField();
        txtBook_Supplier = new javax.swing.JTextField();
        txtBook_Cost = new javax.swing.JTextField();
        txtDepartment_Name = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSave_Book_Entry = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate_Book_Entry = new javax.swing.JButton();
        btnDelete_Book_Entry = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnFirst_Entry_Book_Entry = new javax.swing.JButton();
        btnPrevious_Book_Entry = new javax.swing.JButton();
        btnNext_Book_Entry = new javax.swing.JButton();
        btnLast_Entry_Book_Entry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 84, 44));
        jLabel4.setText("Book ID : ");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 84, 44));
        jLabel5.setText("Book Name : ");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 84, 44));
        jLabel6.setText("Book Author : ");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 84, 44));
        jLabel7.setText("Book Publication : ");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 84, 44));
        jLabel8.setText("Book Supplier : ");

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 84, 44));
        jLabel9.setText("Book Cost : ");

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 84, 44));
        jLabel10.setText("Department Name : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(12, 12, 12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtBook_Cost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtBook_Supplier, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBook_Publication, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBook_Author, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBook_Name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBook_ID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDepartment_Name))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBook_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtBook_Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBook_Publication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtBook_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtBook_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtBook_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDepartment_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave_Book_Entry.setText("Save_It");
        btnSave_Book_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_Book_EntryActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnUpdate_Book_Entry.setText("Update");

        btnDelete_Book_Entry.setText("Delete");
        btnDelete_Book_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete_Book_EntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave_Book_Entry, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(btnUpdate_Book_Entry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete_Book_Entry, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave_Book_Entry, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete_Book_Entry, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btnUpdate_Book_Entry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFirst_Entry_Book_Entry.setText("First Entry");
        btnFirst_Entry_Book_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst_Entry_Book_EntryActionPerformed(evt);
            }
        });

        btnPrevious_Book_Entry.setText("Previous");
        btnPrevious_Book_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious_Book_EntryActionPerformed(evt);
            }
        });

        btnNext_Book_Entry.setText("Next");
        btnNext_Book_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext_Book_EntryActionPerformed(evt);
            }
        });

        btnLast_Entry_Book_Entry.setText("Last Entry");
        btnLast_Entry_Book_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast_Entry_Book_EntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLast_Entry_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevious_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFirst_Entry_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst_Entry_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast_Entry_Book_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funny cartoon.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave_Book_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_Book_EntryActionPerformed
        // TODO add your handling code here:

        Add_Book_EntryData objBook_Entry = new Add_Book_EntryData();

        objBook_Entry.setBook_ID(Integer.parseInt(txtBook_ID.getText()));
        objBook_Entry.setBook_Name(txtBook_Name.getText());
        objBook_Entry.setBook_Publication(txtBook_Publication.getText());
        objBook_Entry.setBook_Author(txtBook_Author.getText());
        objBook_Entry.setBook_Supplier(txtBook_Supplier.getText());
        objBook_Entry.setBook_Cost(Integer.parseInt(txtBook_Cost.getText()));
        objBook_Entry.setDepartment_Name(txtDepartment_Name.getText());

        DBOperation objDBook_Entry = new DBOperation();
        String result = objDBook_Entry.addBookRecord(objBook_Entry);
        if(result.equals("added"))
        {
            System.out.println("");
            JOptionPane.showMessageDialog(this,"Record is added successfully");
        }
        else
        {
            System.out.println("record is not added");
            JOptionPane.showMessageDialog(this,"Please Enter The Correct Value");

        }
    }//GEN-LAST:event_btnSave_Book_EntryActionPerformed

    private void btnDelete_Book_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete_Book_EntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete_Book_EntryActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtBook_ID.setText(" ");
        txtBook_Name.setText(" ");
        txtBook_Author.setText(" ");
        txtBook_Publication.setText(" ");
        txtBook_Supplier.setText(" ");
        txtBook_Cost.setText(" ");
        txtDepartment_Name.setText(" ");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnLast_Entry_Book_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast_Entry_Book_EntryActionPerformed
        // TODO add your handling code here:
        if(alst.size() > 0)
	{
		Add_Book_EntryData Bean = (Add_Book_EntryData)alst.get(alst.size()-1);
		showRecord(Bean);
}

    }//GEN-LAST:event_btnLast_Entry_Book_EntryActionPerformed

    private void btnPrevious_Book_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious_Book_EntryActionPerformed
        // TODO add your handling code here:
        count --;
	if(alst.size()>0)
	{
		Add_Book_EntryData Bean = (Add_Book_EntryData)alst.get(count);
		showRecord(Bean);
}

    }//GEN-LAST:event_btnPrevious_Book_EntryActionPerformed

    private void btnFirst_Entry_Book_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst_Entry_Book_EntryActionPerformed
        // TODO add your handling code here:
        count = 0;
	if(alst.size() >0)
	{
		Add_Book_EntryData Bean = (Add_Book_EntryData)alst.get(count);
		showRecord(Bean);
        }

    }//GEN-LAST:event_btnFirst_Entry_Book_EntryActionPerformed

    private void btnNext_Book_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext_Book_EntryActionPerformed
        // TODO add your handling code here:
        count ++;
	if(alst.size()>0)
	{
                Add_Book_EntryData Bean = (Add_Book_EntryData)alst.get(count);
		showRecord(Bean);
        }

    }//GEN-LAST:event_btnNext_Book_EntryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete_Book_Entry;
    private javax.swing.JButton btnFirst_Entry_Book_Entry;
    private javax.swing.JButton btnLast_Entry_Book_Entry;
    private javax.swing.JButton btnNext_Book_Entry;
    private javax.swing.JButton btnPrevious_Book_Entry;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave_Book_Entry;
    private javax.swing.JButton btnUpdate_Book_Entry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtBook_Author;
    private javax.swing.JTextField txtBook_Cost;
    private javax.swing.JTextField txtBook_ID;
    private javax.swing.JTextField txtBook_Name;
    private javax.swing.JTextField txtBook_Publication;
    private javax.swing.JTextField txtBook_Supplier;
    private javax.swing.JTextField txtDepartment_Name;
    // End of variables declaration//GEN-END:variables
}
