/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainingplacement;

import bean.AddCompanyDetailBean;
import db.DBOperations;
import javax.swing.JOptionPane;

/**
 *
 * @author RG
 */
public class AddCompanyDetail extends javax.swing.JFrame {

    /**
     * Creates new form AddCompanyDetail
     */
    public AddCompanyDetail() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setBounds(400, 40, 500, 500);
        setSize(500, 500);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCompanyType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtHRName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtPinCode = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Company Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 50, 150, 22);
        getContentPane().add(txtCompanyType);
        txtCompanyType.setBounds(240, 90, 129, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Company Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 140, 22);
        getContentPane().add(txtCompanyName);
        txtCompanyName.setBounds(240, 50, 129, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("HR Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 120, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 170, 80, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(52, 200, 90, 22);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Street");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(52, 240, 90, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("City");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(52, 280, 90, 22);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Pin Code");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 320, 100, 22);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(240, 160, 129, 20);
        getContentPane().add(txtPhone);
        txtPhone.setBounds(240, 200, 129, 20);
        getContentPane().add(txtHRName);
        txtHRName.setBounds(240, 130, 129, 20);
        getContentPane().add(txtCity);
        txtCity.setBounds(240, 280, 129, 20);
        getContentPane().add(txtPinCode);
        txtPinCode.setBounds(240, 320, 129, 20);
        getContentPane().add(txtStreet);
        txtStreet.setBounds(240, 240, 129, 20);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(235, 369, 99, 23);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 370, 72, 23);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Company Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 50, 150, 22);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Company Detail");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(150, 10, 240, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/master03_background.gif"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, -20, 530, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String name = txtCompanyName.getText();
        String companytype = txtCompanyType.getText();
        String hrname = txtHRName.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String street = txtStreet.getText();
        String city = txtCity.getText();
        String pin = txtPinCode.getText();
        
        AddCompanyDetailBean obj = new AddCompanyDetailBean();
        obj.setName(name);
        obj.setCompanyType(companytype);
        obj.setHr_name(hrname);
        obj.setEmail(email);
        obj.setPhone(phone);
        obj.setStreet(street);
        obj.setCity(city);
        obj.setPin(pin);
        
        db.DBOperations dbObj = new DBOperations();
        String result =dbObj.insertCompanyRecord(obj);
        
        if(result.equals("valid"))
        {
            JOptionPane.showMessageDialog(null,"company detail is addedd");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        txtCompanyName.setText("");
        txtCompanyType.setText("");
        txtHRName.setText("");
         txtEmail.setText("");
         txtPhone.setText("");
       txtStreet.setText("");
        txtCity.setText("");
        txtPinCode.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompanyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompanyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompanyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompanyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCompanyDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCompanyType;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHRName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPinCode;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
