/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainingplacement;

import java.awt.Toolkit;

/**
 *
 * @author RG
 */
public class HRMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form HRMainFrame
     */
    public HRMainFrame() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStudentRegistration = new javax.swing.JButton();
        btnAddCompanyDetail = new javax.swing.JButton();
        btnCompanySchedule = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/333.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 90, 930, 200);

        btnStudentRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stude.png"))); // NOI18N
        btnStudentRegistration.setText("Report");
        getContentPane().add(btnStudentRegistration);
        btnStudentRegistration.setBounds(700, 310, 210, 210);

        btnAddCompanyDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/company.png"))); // NOI18N
        btnAddCompanyDetail.setText("Add Company Detail");
        btnAddCompanyDetail.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddCompanyDetail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddCompanyDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompanyDetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCompanyDetail);
        btnAddCompanyDetail.setBounds(160, 310, 220, 220);

        btnCompanySchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/schdelue.png"))); // NOI18N
        btnCompanySchedule.setText("Schedule Information");
        btnCompanySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompanySchedule);
        btnCompanySchedule.setBounds(430, 310, 220, 220);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("company Reports");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(730, 540, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Add Company Detail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 550, 160, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Schedule Information");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 550, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCompanyDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompanyDetailActionPerformed
        // TODO add your handling code here:
        AddCompanyDetail obj = new  AddCompanyDetail();
        
    }//GEN-LAST:event_btnAddCompanyDetailActionPerformed

    private void btnCompanyScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyScheduleActionPerformed
        // TODO add your handling code here:
        ScheduleCompany obj = new ScheduleCompany();
    }//GEN-LAST:event_btnCompanyScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCompanyDetail;
    private javax.swing.JButton btnCompanySchedule;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
